Routes to page
ykostov/tennis_rails pull request #3
Opened 2021-01-02 21:52 UTC by ykostov

2021-01-02 23:21 UTC, rmilushev commented on config/routes.rb
>    get 'pages/help'
We have this on row 11, please, remove it.

2021-01-02 23:22 UTC, rmilushev commented on config/routes.rb
> +  # get 'pages/home'
Please, do not remove this line, it is needed for `root to:` routine on line 11.

2021-01-02 23:24 UTC, rmilushev commented on app/views/pages/tour.html.erb
> +<div class="navbar">
We can extract the common `navbar` to a partial file with a name `_navbar.html` and render it on `layout/application.html.erb` template. Use for as a reference our other projects, please.

2021-01-03 09:13 UTC, rmilushev requested changes

2021-01-03 09:13 UTC, rmilushev commented on config/routes.rb
> +  get '', to: "pages#home"
`get` with empty string is not ok :). We have `root` path on row 11, please, remove this.

2021-01-03 09:37 UTC, N-Patarov approved these changes

2021-01-03 09:47 UTC, rmilushev requested changes

2021-01-03 09:47 UTC, rmilushev commented on app/views/layouts/_navbar.html
> +  <a href="/">Home Page </a>
One last touch, please: in Rails, we use `route helpers` in the form:
```
<%= link_to 'Home page', root_path %>
```
Try to refactor the links here to the Rails way, and you will see how easy to use they are. Hint: for example, link to the `ranklist` is: 
```
<%= link_to 'Ranklist', ranklist_path %>
```

2021-01-03 10:21 UTC, rmilushev approved these changes
Looks good to me :+1:

2021-01-03 10:22 UTC, merged